# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Manual build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build Day 1 - Lesson 01
      run: |
        cd src
        javac day1/chapter01/Lab01a.java; java day1.chapter01.Lab01a
        javac day1/chapter01/Lab01b.java; java day1.chapter01.Lab01b
        javac day1/chapter01/Lab01c.java; java day1.chapter01.Lab01c

    - name: Build Day 1 - Lesson 02
      run: |
        cd src
        javac day1/chapter02/Lab02.java; java day1.chapter02.Lab02

    - name: Build Day 1 - Lesson 03
      run: |
        cd src
        javac day1/chapter03/Lab03.java; java day1.chapter03.Lab03
